#pragma once

#define FPS 60
#define DELTA_TIME (    1 / (float) FPS)

// TODO(Tobi): Get rid of this
#define GRID_SIZE 54

#define HEXAGON_A 31
#define HALF_HEXAGON_PIXEL_HEIGHT 27
#define HEXAGON_PIXEL_HEIGHT 54
#define HALF_HEXAGON_PIXEL_WIDTH 31
#define HEXAGON_PIXEL_WIDTH 62


#define TRI_DOWN_TOP 1
#define TRI_DOWN_LEFT 2
#define TRI_DOWN_RIGHT 4

#define TRI_UP_BOTTOM 1
#define TRI_UP_LEFT 2
#define TRI_UP_RIGHT 4


#define TRIANGLE_PAIRS_X 20
#define TRIANGLE_LINE_PAIRS_Y 10
#define TRIANGLE_LINES_Y (TRIANGLE_LINE_PAIRS_Y * 2)

#define TILES_X (TRIANGLE_PAIRS_X * 2 + 1)
#define TILES_Y TRIANGLE_LINES_Y

#define MONSTER_STONE_BAR_WIDTH 24
#define MONSTER_STONE_BAR_HEIGHT 44

#define RIGHT_MENU_WIDTH (GRID_SIZE * 3)

#define WINDOW_WIDTH ((TRIANGLE_PAIRS_X + 1) * HALF_HEXAGON_PIXEL_WIDTH + RIGHT_MENU_WIDTH + MONSTER_STONE_BAR_WIDTH)
#define WINDOW_HEIGHT (TILES_Y * HALF_HEXAGON_PIXEL_HEIGHT)

// NOTE: x-offset; change when using a second monitor
//#define MONITOR_OFFSET 1920

#ifndef MONITOR_OFFSET
    #define MONITOR_OFFSET 0
#endif
